services:
  - type: worker
    name: kogane-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
